In [1]:
import cv2
import numpy as np

In [2]:
a=cv2.imread("C:/Users/SN139/Downloads/trees.jpg")

In [3]:
a

array([[[ 58,  69, 131],
        [ 54,  67, 129],
        [ 55,  73, 134],
        ...,
        [  9, 104,  84],
        [  7, 105,  83],
        [  9, 107,  85]],

       [[ 55,  66, 128],
        [ 51,  65, 124],
        [ 51,  69, 130],
        ...,
        [  8, 100,  81],
        [  6, 101,  80],
        [  8, 103,  82]],

       [[ 44,  58, 117],
        [ 41,  58, 115],
        [ 43,  61, 120],
        ...,
        [  6,  97,  76],
        [  6,  97,  76],
        [  7,  98,  77]],

       ...,

       [[  1,  75,  45],
        [  3,  77,  47],
        [  3,  77,  47],
        ...,
        [  0,  67,  40],
        [  0,  65,  38],
        [  0,  64,  37]],

       [[  0,  74,  44],
        [  2,  76,  46],
        [  2,  76,  46],
        ...,
        [  0,  65,  38],
        [  0,  62,  36],
        [  0,  61,  35]],

       [[  0,  74,  44],
        [  2,  76,  46],
        [  0,  74,  44],
        ...,
        [  0,  64,  37],
        [  0,  62,  36],
        [  0,  60,  34]]

In [4]:
rs=cv2.resize(a,(180,180))

In [5]:
rs

array([[[  0,  58,  59],
        [ 12,  54, 120],
        [  2,  73, 117],
        ...,
        [  0,  79,  66],
        [  2,  81,  68],
        [  9,  79,  69]],

       [[  3,  74,  93],
        [  5, 131, 137],
        [ 17, 114, 174],
        ...,
        [  4,  62,  57],
        [  7, 111,  94],
        [ 20,  91,  75]],

       [[  0,  69,  66],
        [ 11,  21,  35],
        [  0,  36,  48],
        ...,
        [  7,  60,  71],
        [  5,  99,  65],
        [  1,  70,  57]],

       ...,

       [[  1,  17,  23],
        [  8,  86,  62],
        [  2,   8,  53],
        ...,
        [  0,  60,  38],
        [  2,  73,  57],
        [  1,  95,  71]],

       [[  0,  19,  24],
        [  0,  29,  39],
        [  4, 106,  26],
        ...,
        [  1,  71,  35],
        [  3,  70,  54],
        [  3,  90,  64]],

       [[  4,  63,  54],
        [  1,  45,  14],
        [  0,  42,  31],
        ...,
        [  2,  78,  56],
        [  1,  97,  59],
        [  2,  84,  61]]

In [6]:
shape=rs.shape

In [7]:
shape

(180, 180, 3)

In [8]:
height,width=rs.shape[:2]
print(height)
print(width)

180
180


In [9]:
c=(height/2,width/2)
c

(90.0, 90.0)

In [65]:
#ROTATION MATRIX
rm=cv2.getRotationMatrix2D(center=c,angle=90,scale=0.6)

In [66]:
rm

array([[ 3.6739404e-17,  6.0000000e-01,  3.6000000e+01],
       [-6.0000000e-01,  3.6739404e-17,  1.4400000e+02]])

In [67]:
#ROTATED IMAGE
ri=cv2.warpAffine(src=rs,M=rm,dsize=(height,width))

In [68]:
cv2.imshow("Original image",rs)
cv2.waitKey(0)
cv2.imshow("ROTATED IMAGE",ri)
cv2.waitKey(0)
cv2.destroyAllWindows()

-1

# TRANSLATION MATRIX

In [69]:
tx,ty=width/2,height/2

In [70]:
#TRANSLATION MATRIX
tm=np.array([[1,0,tx],[0,1,ty]])

In [71]:
tm

array([[ 1.,  0., 90.],
       [ 0.,  1., 90.]])

In [72]:
ti=cv2.warpAffine(src=rs,M=tm,dsize=(height,width))

In [ ]:
cv2.imshow("Original image",rs)
cv2.waitKey(0)
cv2.imshow("TRANSLATION IMAGE",ti)
cv2.waitKey(0)
cv2.destroyAllWindows()