In [1]:
import cv2
import numpy as np

In [2]:
a=cv2.imread("C:/Users/SN139/Downloads/jpg.jpg",0)

In [3]:
cv2.imshow("img",a)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
a

array([[153, 144, 132, ...,  87,  85,  89],
       [155, 146, 133, ...,  89,  87,  91],
       [158, 147, 136, ...,  91,  89,  93],
       ...,
       [159, 152, 140, ..., 118, 111, 101],
       [162, 154, 142, ..., 119, 111, 101],
       [161, 155, 144, ..., 119, 110, 100]], dtype=uint8)

In [5]:
ret,thres=cv2.threshold(a,153,100,cv2.THRESH_BINARY)

In [6]:
print(ret)

153.0


In [7]:
cv2.imshow("img",thres)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
thres

array([[  0,   0,   0, ...,   0,   0,   0],
       [100,   0,   0, ...,   0,   0,   0],
       [100,   0,   0, ...,   0,   0,   0],
       ...,
       [100,   0,   0, ...,   0,   0,   0],
       [100, 100,   0, ...,   0,   0,   0],
       [100, 100,   0, ...,   0,   0,   0]], dtype=uint8)

# syntax

#syntax:
  ret,varname=cv2.threshold(inputimage,threshold limit,replace value,<threshold type>)

In [9]:
ret,thres1=cv2.threshold(a,153,100,cv2.THRESH_BINARY)
ret,thres2=cv2.threshold(a,153,100,cv2.THRESH_BINARY_INV)
ret,thres3=cv2.threshold(a,153,100,cv2.THRESH_TRUNC)
ret,thres4=cv2.threshold(a,153,100,cv2.THRESH_TOZERO)
ret,thres5=cv2.threshold(a,153,100,cv2.THRESH_TOZERO_INV)

In [10]:
thres1

array([[  0,   0,   0, ...,   0,   0,   0],
       [100,   0,   0, ...,   0,   0,   0],
       [100,   0,   0, ...,   0,   0,   0],
       ...,
       [100,   0,   0, ...,   0,   0,   0],
       [100, 100,   0, ...,   0,   0,   0],
       [100, 100,   0, ...,   0,   0,   0]], dtype=uint8)

In [11]:
thres2

array([[100, 100, 100, ..., 100, 100, 100],
       [  0, 100, 100, ..., 100, 100, 100],
       [  0, 100, 100, ..., 100, 100, 100],
       ...,
       [  0, 100, 100, ..., 100, 100, 100],
       [  0,   0, 100, ..., 100, 100, 100],
       [  0,   0, 100, ..., 100, 100, 100]], dtype=uint8)

In [12]:
thres3

array([[153, 144, 132, ...,  87,  85,  89],
       [153, 146, 133, ...,  89,  87,  91],
       [153, 147, 136, ...,  91,  89,  93],
       ...,
       [153, 152, 140, ..., 118, 111, 101],
       [153, 153, 142, ..., 119, 111, 101],
       [153, 153, 144, ..., 119, 110, 100]], dtype=uint8)

In [13]:
thres4

array([[  0,   0,   0, ...,   0,   0,   0],
       [155,   0,   0, ...,   0,   0,   0],
       [158,   0,   0, ...,   0,   0,   0],
       ...,
       [159,   0,   0, ...,   0,   0,   0],
       [162, 154,   0, ...,   0,   0,   0],
       [161, 155,   0, ...,   0,   0,   0]], dtype=uint8)

In [14]:
thres5

array([[153, 144, 132, ...,  87,  85,  89],
       [  0, 146, 133, ...,  89,  87,  91],
       [  0, 147, 136, ...,  91,  89,  93],
       ...,
       [  0, 152, 140, ..., 118, 111, 101],
       [  0,   0, 142, ..., 119, 111, 101],
       [  0,   0, 144, ..., 119, 110, 100]], dtype=uint8)

In [ ]:
cv2.imshow("img1",thres1)
cv2.waitKey(0)
cv2.imshow("img1",thres2)
cv2.waitKey(0)
cv2.imshow("img1",thres3)
cv2.waitKey(0)
cv2.imshow("img1",thres4)
cv2.waitKey(0)
cv2.imshow("img1",thres5)
cv2.waitKey(0)
cv2.destroyAllWindows()